# Generated by Django 6.0 on 2026-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('probability', models.FloatField(default=0)),
                ('sample_size', models.IntegerField(default=0)),
                ('is_confident', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
